# PortfolioProject/settings.py
# ----------------------------------------------------------------------------------------------------

"""
Django settings for PortfolioProject project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os # -----

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9no(=r3ftzp1@^ky1oc2q*u$gtx*&jq0t_1%t_+zg9a=#ip36j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'finance_app',  # finance application logic -----
    'portfolio_app',  # portfolio pages -----
    'accounts.apps.AccountsConfig'  # user accounts (login/signup) - Removed .apps.AccountsConfig for simplicity -----
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PortfolioProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # Template directory -----
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PortfolioProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = 'static/'

# Tell Django where to look for top-level static files (like your root /static/ folder)
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Use the Path object for clean joining
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.CustomUser'

# --- Authentication Redirect URLs ---
# Directs to the URL pattern named 'login'
LOGIN_URL = 'accounts:login' 
# After successful login, redirects user to the URL pattern named 'dashboard'
LOGIN_REDIRECT_URL = 'accounts:mypage' 
# After successful logout, redirects user to the URL pattern named 'home'
LOGOUT_REDIRECT_URL = 'portfolio_app:home'

# Email Backend (Console for testing)
# Temporarily set to console to see emails in the terminal
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# SMTP Settings (Commented out for production/later use)
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# DEFAULT_FROM_EMAIL = 'password_reset@gmail.com'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'your_email@gmail.com' # -----
# EMAIL_HOST_PASSWORD = "your_app_password" # -----
# EMAIL_USE_TLS = True
